
# Cache setup: 
# This is the cache locker so this is where the cached copies will live
proxy_cache_path /var/cache/nginx/hosp
                 levels=1:2
                 keys_zone=hosp_cache:10m
                 max_size=100m
                 inactive=10m
                 use_temp_path=off;

# Forwarding setup:
upstream hosp {
    server ciao-reliability-server.animal-hospital.mkrs.link:80;
}

# This is our own proxy server health checker
server {
    listen 80;
    server_name _;   # respond to any hostname
    location = /health {
        access_log off;
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }

# Forward everything else to HOSP
    location / {
    proxy_pass http://hosp;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # HOSP has a 9 second wait, instructions to timeout:
    proxy_connect_timeout 5s;
    proxy_read_timeout 10;
    proxy_send_timeout 10s;


    #Caching 

    proxy_cache hosp_cache;

    # Cache the successful reads too to reuse if needed

    proxy_cache_valid 200 302 30s;

    #cache the 404s for a bit

    proxy_cache_valid 404 5s;

    # Serve last known good chaced copy: 

    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;

    # Protect against high traffic 
    proxy_cache_lock on; 
}
}